#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

filter="$1"

cd $script_dir

scripts=$(find ./runs -maxdepth 1 -mindepth 1 -perm +111 -type f)

for script in $scripts; do
    if echo "$script" | grep -qv "$filter"; then
        echo "filtering $filter"
        continue 
    fi

    ./$script
done
